server:
  port: 8080
  servlet:
     context-path: /oktademo

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
#    org.springframework.boot.autoconfigure: DEBUG


okta:
  oauth2:
    issuer: https://{url}.com/oauth2/default
    client-id: {client-id}
    client-secret: {client-secret}
