server:
  port: 8080
  servlet:
     context-path: /oktademo2

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: {client-id}
            client-secret: {client-secret}
        provider:
          okta:
            issuer-uri: https://{url}.com/oauth2/default
            client-name: Okta
